"""
legacy/agent/export_bundle.py
==============================
Portable export bundle for heirs.

The heir should not have to navigate the owner's data directory:
they receive a self-contained directory (for a USB drive or notarial backup)
with everything needed to understand and verify the legacy:

  bundle/
   HEIR_GUIDE.md          prioritized guide (heir_guide)
   README.txt             what this is and how to use it
   audit.db               copy of the audit trail (WAL-safe backup)
   verify_legacy.py       stdlib-only verifier (when available)
   artifacts/             encrypted artifacts (AES-256-GCM, unchanged)
   MANIFEST.json          SHA-256 of every bundle file

Design decisions:
  - audit.db is copied through SQLite's backup API, not by copying the file:
    in WAL mode, copying the file can omit recent transactions still in -wal.
  - BUNDLE_EXPORTED is appended before the backup, so the bundle records its
    own export in the chain it carries.
  - artifacts travel encrypted: the bundle can be lost without exposing
    content. Restoring them requires the passphrase (see README).
  - when a passphrase is provided, every artifact is verified before export;
    a corrupt bundle is never delivered (fail closed).
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

BUNDLE_VERSION = "1"

_README = """\
DIGITAL LEGACY  BUNDLE for heirs
========================================

This directory was generated by Digital Legacy on {ts}
for the legacy of: {owner}

Contents:
  HEIR_GUIDE.md          read this first: what exists and where to begin.
  audit.db               sealed record of every operation on the legacy.
  verify_legacy.py       independent verifier (requires only Python 3).
  artifacts/             encrypted copies of archived documents.
  MANIFEST.json          SHA-256 fingerprint of every bundle file.

To verify that the record was not tampered with:

    python3 verify_legacy.py audit.db

To restore an encrypted document (requires Digital Legacy and the vault
passphrase, delivered through the channel designated by the owner):

    legacy restore <hash> --output <destination>

If a MANIFEST hash does not match its file, the bundle was altered after
creation: do not trust it and request a new copy.
"""


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def export_bundle(
    agent,
    dest: Path,
    *,
    actor: str,
    passphrase: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Export the bundle to `dest` (a new or empty directory).

    agent      : LegacyAgent with the vault unlocked.
    actor      : who exports it (remains in the audit trail).
    passphrase : when provided, each archived artifact is verified before
                 inclusion; a corrupt artifact aborts the export.

    returns the manifest (also written as MANIFEST.json).
    """
    if not agent._unlocked or agent._index is None:
        raise RuntimeError("Vault is locked. Unlock it before exporting.")

    dest = Path(dest)
    if dest.exists() and any(dest.iterdir()):
        raise ValueError(f"Destination {dest} exists and is not empty.")
    dest.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).isoformat()

    # Generate the heir guide.
    guide = agent.heir_guide(actor=actor)
    (dest / "HEIR_GUIDE.md").write_text(guide, encoding="utf-8")

    # Write the bundle README.
    (dest / "README.txt").write_text(
        _README.format(ts=ts, owner=agent._index.owner_id), encoding="utf-8"
    )

    # Verify archived artifacts when possible.
    hashes: List[str] = agent._store.list_hashes()
    if passphrase is not None or agent._index.store_key_hex:
        bad = [h for h in hashes if not agent.verify_artifact(h, passphrase)]
        if bad:
            raise ValueError(
                "Export aborted: corrupt or tampered artifacts: "
                + ", ".join(h[:16] + "..." for h in bad)
            )
    for h in hashes:
        src = agent._store._path_for(h)
        out = dest / "artifacts" / h[:2] / f"{h}.enc"
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, out)

    # Include the standalone verifier when available.
    verify_src = Path(__file__).resolve().parents[2] / "verify_legacy.py"
    verify_included = verify_src.is_file()
    if verify_included:
        shutil.copyfile(verify_src, dest / "verify_legacy.py")

    # Record the export before taking the WAL-safe audit backup.
    agent._audit.append(
        "BUNDLE_EXPORTED",
        actor=actor,
        detail=f"dest={dest.name} artifacts={len(hashes)} "
               f"verified={passphrase is not None}",
    )
    src_conn = sqlite3.connect(agent._data_dir / "audit.db")
    dst_conn = sqlite3.connect(dest / "audit.db")
    try:
        src_conn.backup(dst_conn)
    finally:
        dst_conn.close()
        src_conn.close()

    # Build the manifest after all bundle files are present.
    files = {
        str(p.relative_to(dest)): _sha256_file(p)
        for p in sorted(dest.rglob("*"))
        if p.is_file() and p.name != "MANIFEST.json"
    }
    manifest: Dict[str, Any] = {
        "bundle_version": BUNDLE_VERSION,
        "created_at": ts,
        "owner_id": agent._index.owner_id,
        "actor": actor,
        "audit": {
            "length": agent._audit.length,
            "tip_hash": agent._audit.tip_hash,
        },
        "artifacts_included": len(hashes),
        "artifacts_verified": passphrase is not None or bool(agent._index.store_key_hex),
        "verify_script_included": verify_included,
        "files": files,
    }
    (dest / "MANIFEST.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=True),
        encoding="utf-8",
    )
    return manifest


def check_manifest(bundle_dir: Path) -> List[str]:
    """
    Re-verify the hashes in a bundle's MANIFEST.json.
    Return the list of problems (empty means intact).
    """
    bundle_dir = Path(bundle_dir)
    manifest_path = bundle_dir / "MANIFEST.json"
    if not manifest_path.is_file():
        return ["MANIFEST.json missing"]
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"MANIFEST.json unreadable: {exc}"]

    problems: List[str] = []
    for rel, expected in manifest.get("files", {}).items():
        p = bundle_dir / rel
        if not p.is_file():
            problems.append(f"missing {rel}")
        elif _sha256_file(p) != expected:
            problems.append(f"hash mismatch: {rel}")
    return problems
